language: python
python:
  - "3.6"

script: python -m unittest *_test.py *_slowtest.py
branches:
  only:
    - master

notifications:
  email:
    recipients:
      - "suurkivi+travisci@gmail.com"
    on_success: change
    on_failure: always
