language: python
python:
  - "3.6"

script: invoke test --slow
branches:
  only:
    - master

notifications:
  email:
    recipients:
      - "suurkivi+travisci@gmail.com"
    on_success: change
    on_failure: always
