language: python
python:
  - "3.6"

script: python solutions_test.py
branches:
  only:
    - master

notifications:
  email:
    recipients:
      - "suurkivi+travisci@gmail.com"
    on_success: always
    on_failure: always